AStore/AStore/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AStore.Core.Concrete;

namespace AStore.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

AStore/AStore/Models/ContactsViewModel.cs
using AStore.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AStore.Models
{
    public class ContactsViewModel
    {
            public List<Contacts> Contacts { get; set; }
    }
}

AStore/AStore/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AStore.Data;

namespace AStore.Models
{
    public class ProductViewModel
    {
        public string CategoryName { get; set; }
        public List<Product> Products { get; set; } 
    }
}

AStore/AStore/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AStore.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult About()
        {
            return View();
        }
    }
}

AStore/AStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AStore.Core.Abstract;
using AStore.Core.Concrete;
using AStore.Core.Helpers;
using AStore.Models;

namespace AStore.Controllers
{
    public class CartController : Controller
    {
        private IAstoreRepository _astoreRepository;

        public CartController(IAstoreRepository repository)
        {
            _astoreRepository = repository;
        }

        // GET: Cart
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = GetCart(),
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(int productId, string returnUrl)
        {
            var product = _astoreRepository.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                GetCart().AddItem(product, 1);
            }
            // TODO: maybe will change this part to avoid redirection
            return RedirectToAction("Index", new {returnUrl});
        }

        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            var product = _astoreRepository.Products.FirstOrDefault(x => x.Id == productId);
            if (product != null)
            {
                // TODO: implement to remove more then 1 item
                GetCart().RemoveProduct(product, -1);
            }
            // TODO: maybe will change this part to avoid redirection
            return RedirectToAction("Index", new {returnUrl});
        }

        private Cart GetCart()
        {
            var cart = (Cart) Session[StaticData.SessionCartKey];
            if (cart == null)
            {
                cart = new Cart();
                Session[StaticData.SessionCartKey] = cart;
            }
            return cart;
        }
    }
}

AStore/AStore/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AStore.Core.Abstract;
using AStore.Models;

namespace AStore.Controllers
{
    public class ContactsController : Controller
    {
        private IAstoreRepository _astoreRepository;

        public ContactsController(IAstoreRepository repository)
        {
            this._astoreRepository = repository;
        }

        // GET: Contacts
        public ActionResult Contacts()
        {
            return View();
        }
    }
}

AStore/AStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AStore.Core.Abstract;

namespace AStore.Controllers
{
    public class HomeController : Controller
    {
        private IAstoreRepository _astoreRepository;

        public HomeController(IAstoreRepository repository)
        {
            _astoreRepository = repository;
        }

        // GET: Home
        public ViewResult Index()
        {
            //var data = _astoreRepository.Products.ToList();
            return View();
        }
    }
}

AStore/AStore/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AStore.Core.Abstract;
using AStore.Core.Helpers;

namespace AStore.Controllers
{
    public class NavController : Controller
    {
        private IAstoreRepository _astoreRepository;

        public NavController(IAstoreRepository repository)
        {
            _astoreRepository = repository;
        }

        // GET: Nav
        public PartialViewResult Menu()
        {
            var categories = StaticData.Categories;
            return PartialView(categories);
        }
    }
}

AStore/AStore/Controllers/PaymentAndDeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AStore.Core.Abstract;

namespace AStore.Controllers
{
    public class PaymentAndDeliveryController : Controller
    {
        private IAstoreRepository _astoreRepository;

        public PaymentAndDeliveryController(IAstoreRepository repository)
        {
            _astoreRepository = repository;
        }

        // GET: PaymentAndDelivery
        public ActionResult PaymentAndDelivery()
        {
            return View();
        }
    }
}

AStore/AStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using AStore.Core.Abstract;
using AStore.Models;

namespace AStore.Controllers
{
    public class ProductController : Controller
    {
        private IAstoreRepository _astoreRepository;

        public ProductController(IAstoreRepository repository)
        {
            this._astoreRepository = repository;
        }

        public ViewResult List(string category, int page = 1)
        {
            var model = new ProductViewModel
            {
                CategoryName = category,
                Products = _astoreRepository.Products.Where(x => x.Categories.Name == category).ToList()
            };
            return View(model);
        }
    }
}

AStore/AStore/Views/About/About.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - About</title>
    <link href="~/Content/About.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <section id="content">
        <div id="breadcrumb-container">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <header class="content-title">
                        <h1 class="title">
                            @ViewRes.About.AboutUs
                        </h1>
                        <p class="title-desc">
                            Мы самые клевые и ваще.
                        </p>
                    </header>
                    <div class="xs-margin">
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-sm-8 col-xs-12">
                            <div class="text-page">
                                <h3>@ViewRes.About.Title блаблабла.</h3>
                                <p class="image">
                                    <img src="http://i.rozetka.com.ua/design/about/new_office.png" title="Магазин AStore" alt="Магазин AStore" border="0px">
                                </p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                                <p>Мы самые крутые и доставим что угодно и куда угодно.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AStore/AStore/Views/Cart/Cart.cshtml
<div class="container">
    <div class="col-md-12">
        <header class="content-title">
            <h1 class="title">Shopping Cart</h1>
        </header>
        <div class="xs-margin"></div>
        <div class="row">
            <div class="col-md-12 table-responsive">
                <table class="table cart-table">
                    <thead>
                    <tr>
                        <th class="table-title">@ViewRes.Cart.ProductNameHeader</th>
                        <th class="table-title">@ViewRes.Cart.ProductCodeHeader</th>
                        <th class="table-title">@ViewRes.Cart.UnitPriceHeader</th>
                        <th class="table-title">@ViewRes.Cart.QuantityHeader</th>
                        <th class="table-title">@ViewRes.Cart.SubTotalHeader</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

AStore/AStore/Views/Cart/Index.cshtml
@model AStore.Models.CartIndexViewModel

<div class="container">
    <div class="col-md-12">
        <header class="content-title">
            <h1 class="title">@ViewRes.Cart.CartHeader</h1>
        </header>
        <div class="xs-margin"></div>
        <div class="row">
            <div class="col-md-12 table-responsive">
                <table class="table cart-table">
                    <thead>
                    <tr>
                        <th class="table-title">@ViewRes.Cart.ProductNameHeader</th>
                        <th class="table-title">@ViewRes.Cart.ProductCodeHeader</th>
                        <th class="table-title">@ViewRes.Cart.UnitPriceHeader</th>
                        <th class="table-title">@ViewRes.Cart.QuantityHeader</th>
                        <th class="table-title">@ViewRes.Cart.SubTotalHeader</th>
                    </tr>
                    </thead>
                    @foreach (var item in Model.Cart.Lines)
                    {
                        <tr>
                            <td class="item-name-col">
                                <header class="item-name">@item.Product.Name</header>
                            </td>
                            <td class="item-code">@item.Product.Name</td>
                            <td class="item-price-col">
                                <span class="item-price-special">@item.Product.Price</span>
                            </td>
                            <td>
                                <div class="custom-quantity-input">
                                    <input type="text" name="quantity" value="@item.Quantity"/>
                                    <a href="#" onclick=" return!1 " class="quantity-btn quantity-input-up"><i class="fa fa-angle-up"></i></a>
                                    <a href="#" onclick=" return!1 " class="quantity-btn quantity-input-down"><i class="fa fa-angle-down"></i></a>
                                </div>
                            </td>
                            <td class="item-total-col">
                                <span class="item-price-special">@(item.Product.Price*item.Quantity)</span>
                                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                                {
                                    @Html.Hidden("productId", item.Product.Id)
                                    @Html.HiddenFor(x => x.ReturnUrl)
                                    <input class="btn btn-sm btn-warning" type="submit" value="@ViewRes.Cart.DeleteProductBtn"/>
                                }
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="lg-margin"></div>
            <div class="row">
                <div class="col-md-8 col-sm-12 col-xs-12 lg-margin"></div>
                <div class="col-md-4 col-sm-12 col-xs-12">
                    <table class="table total-table">
                        <tfoot>
                        <tr>
                            <td>@ViewRes.Cart.TotalCaption</td>
                            <td>@Model.Cart.ComputeTotalValue()</td>
                        </tr>
                        </tfoot>
                    </table>
                    <div class="md-margin"></div>
                    <a href="#" class="btn btn-custom">@ViewRes.Cart.ContinueShoppingButton</a>
                    <a href="#" class="btn btn-custom">@ViewRes.Cart.Checkout</a>
                </div>
            </div>
            <div class="md-margin2x"></div>
        </div>
    </div>
</div>

AStore/AStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "AStore";
}

AStore/AStore/Views/Nav/Menu.cshtml
@model IEnumerable<AStore.Data.Categories>

<nav class="navbar ">
    <div class="container-fluid">
        <div>
            <ul class="nav navbar-nav">
                <li class="active">
                    @Html.ActionLink(ViewRes.Menu.Home, "Index", "Home", null, null)
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">@ViewRes.Menu.Products<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @foreach (var link in Model)
                        {
                            <li>
                                @Html.RouteLink(link.Name, new
                            {
                                controller = "Product",
                                action = "List",
                                category = link.Name,
                                page = 1
                            })
                            </li>
                        }
                    </ul>
                </li>
                <li class="">
                    @Html.ActionLink(ViewRes.Menu.PaymentAndDelivery, "PaymentAndDelivery", "PaymentAndDelivery", null, null)
                </li>
                <li>
                    @Html.ActionLink(ViewRes.Menu.Contacts, "Contacts", "Contacts", null, null)
                </li>
                <li>
                    @Html.ActionLink(ViewRes.Menu.About, "About", "About", null, null)
                </li>
            </ul>
        </div>
        <div id="quick-access">
            <div class="dropdown-cart-menu-container pull-right">
                <div class="btn-group dropdown-cart">
                    <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown"><span class="cart-menu-icon"></span> 0 item(s) <span class="drop-price">- $0.00</span></button>
                    <div class="dropdown-menu dropdown-cart-menu pull-right clearfix" role="menu">
                        <p class="dropdown-cart-description">Recently added item(s).</p><ul class="dropdown-cart-product-list">
                            <li class="item clearfix">
                                <a href="http://newsmartwave.net/html/venedor/green/index.html#" title="Delete item" class="delete-item"><i class="fa fa-times"></i></a> <a href="http://newsmartwave.net/html/venedor/green/index.html#" title="Edit item" class="edit-item"><i class="fa fa-pencil"></i></a><figure><a href="http://newsmartwave.net/html/venedor/green/product.html"><img src="item12.jpg" alt="phone 4"></a></figure>
                                <div class="dropdown-cart-details">
                                    <p class="item-name">
                                        <a href="http://newsmartwave.net/html/venedor/green/product.html">Cam Optia AF Webcam</a>
                                    </p>
                                    <p>1x <span class="item-price">$499</span></p>
                                </div>
                            </li>
                            <li class="item clearfix">
                                <a href="http://newsmartwave.net/html/venedor/green/index.html#" title="Delete item" class="delete-item"><i class="fa fa-times"></i></a> <a href="http://newsmartwave.net/html/venedor/green/index.html#" title="Edit item" class="edit-item"><i class="fa fa-pencil"></i></a><figure><a href="http://newsmartwave.net/html/venedor/green/product.html"><img src="item13.jpg" alt="phone 2"></a></figure>
                                <div class="dropdown-cart-details">
                                    <p class="item-name">
                                        <a href="http://newsmartwave.net/html/venedor/green/product.html">Iphone Case Cover Original</a>
                                    </p>
                                    <p>1x <span class="item-price">$499<span class="sub-price">.99</span></span></p>
                                </div>
                            </li>
                        </ul><ul class="dropdown-cart-total"><li><span class="dropdown-cart-total-title">Shipping:</span>$7</li><li><span class="dropdown-cart-total-title">Total:</span>$1005<span class="sub-price">.99</span></li></ul>
                        <div class="dropdown-cart-action">
                            <p>
                                <a href="http://newsmartwave.net/html/venedor/green/cart.html" class="btn btn-custom-2 btn-block">Cart</a>
                            </p>
                            <p>
                                <a href="http://newsmartwave.net/html/venedor/green/checkout.html" class="btn btn-custom btn-block">Checkout</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <form class="form-inline quick-search-form" role="form" action="http://newsmartwave.net/html/venedor/green/index.html#">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search here">
                </div><button type="submit" id="quick-search" class="btn btn-custom"></button>
            </form>
        </div>
    </div>
</nav>

AStore/AStore/Views/PaymentAndDelivery/PaymentAndDelivery.cshtml
@{
    ViewBag.Title = "PaymentAndDelivery";
}

AStore/AStore/Views/Product/List.cshtml
@model AStore.Models.ProductViewModel

@{
    ViewBag.Title = "List";
}

<div style="width: 1170px; text-align: center; margin: 0 auto">
    @foreach (var product in Model.Products)
    {
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="item item-hover">
                <div class="item-image-wrapper">
                    <figure class="item-image-container">
                        <img src="/images/item4-hover.jpg" alt="item1" class="item-image">
                    </figure>
                    <div class="item-price-container">
                        <span class="item-price">@product.Price</span>
                    </div>
                </div>
                <div class="item-meta-container">
                    <h3 class="item-name">
                        <a href="product.html">@product.Name</a>
                    </h3>
                    <div class="item-action">
                        @using (Html.BeginForm("AddToCart", "Cart"))
                        {
                            @Html.Hidden("productId", product.Id)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <input type="submit" class="btn btn-success" value="Add to Cart"/>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

AStore/AStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewRes.Layout.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    
        <header id="header">
            <div id="header-top">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="header-top-left">
                                <ul id="top-links" class="clearfix">
                                    <li><a href="http://newsmartwave.net/html/venedor/green/index.html#" title="@ViewRes.Layout.Account"><span class="top-icon top-icon-user"></span><span class="hide-for-xs">@ViewRes.Layout.Account</span></a></li>
                                    <li><span class="top-icon top-icon-cart"/>@Html.ActionLink(ViewRes.Layout.Cart, "Cart", "Cart", null, null)</li>
                                </ul>
                            </div>
                            <div class="header-top-right">
                                <div class="header-top-dropdowns pull-right">
                                    <div class="btn-group dropdown-language">
                                        <button type="button" class="btn btn-custom dropdown-toggle" data-toggle="dropdown"><span class="flag-container"><img src="england-flag.png" alt="flag of england"></span> <span class="hide-for-xs">English</span></button>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            <li><a href="http://newsmartwave.net/html/venedor/green/index.html#"><span class="flag-container"><img src="italy-flag.png" alt="flag of england"></span><span class="hide-for-xs">Italian</span></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="header-text-container pull-right">
                                    <p class="header-text">Welcome to AStore!</p>
                                    <p class="header-link">
                                        <a href="http://newsmartwave.net/html/venedor/green/index.html#">login</a>&nbsp;or&nbsp;<a href="http://newsmartwave.net/html/venedor/green/index.html#">create an account</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="inner-header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5 col-sm-5 col-xs-12 logo-container">
                            <h1 class="logo clearfix"> <a href="index.html" title="AStore eCommerce Template"><img src="/Images/logo.png" alt="AStore Commerce Template" width="238" height="76"></a></h1>
                        </div>
                        <div class="col-md-7 col-sm-7 col-xs-12 header-inner-right">
                            <div class="header-box pull-right" style="width: 180px;">
                                <ul style="margin-bottom: 0px;">
                                    <li><span class="header-box-icon header-box-icon-skype"></span>astore_support</li>
                                    <li><span class="header-box-icon header-box-icon-email"></span><a href="mailto:mail@mail.com">mail@mail.com</a></li>
                                </ul>
                            </div>
                            <div class="header-box contact-phones pull-right clearfix">
                                <span class="header-box-icon header-box-icon-earphones"></span>
                                <ul class="pull-left">
                                    <li>+(404) 111 11 11 11</li>
                                    <li>+(404) 111 11 11 11</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="main-nav-container">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 clearfix">
                                @Html.Action("Menu", "Nav")
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section id="content">
            @RenderBody()
        </section>
        <footer id="footer">
            <div id="inner-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-sm-5 col-xs-12 widget">
                            <h3>MY ACCOUNT</h3>
                            <ul class="links">
                                <li><a href="http://google.com">My account</a></li>
                                <li><a href="http://google.com">Personal information</a></li>
                                <li><a href="http://google.com">Addresses</a></li>
                                <li><a href="http://google.com">Discount</a></li>
                                <li><a href="http://google.com">Order History</a></li>
                            </ul>
                        </div>
                        <div class="col-md-4 col-sm-5 col-xs-12 widget">
                            <h3>INFORMATION</h3>
                            <ul class="links">
                                <li><a href="http://google.com">Our stores</a></li>
                            </ul>
                        </div>
                        <div class="col-md-4 col-sm-5 col-xs-12 widget">
                            <h3>Contacts</h3>
                            <ul class="contact-list">
                                <li><strong>AStore</strong></li>
                                <li>UA</li>
                                <li>ALL UA</li>
                                <li>UA UA</li>
                                <li>UA UA UA</li>
                                <li>Working Days: Mon. - Sun.</li>
                                <li>Working Hours: 9.00AM - 8.00PM</li>
                            </ul>
                        </div>
                        <div class="clearfix visible-sm"></div>
                    </div>
                </div>
            </div>
            <div id="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5 col-sm-5 col-xs-12 footer-text-container">
                            <p>© 2015 Powered by AStore™. All Rights Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>